services: 
# will add volumes to persist data once successfully transferring data
  backend: 
    build: ./backend
    ports: 
      - "8000:8000"
    # idk if this volumes thing is right here
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=user
      - DB_PASS=temp
    depends_on: 
      db: 
        condition: service_healthy

  frontend: 
    build: ./frontend
    ports: 
      - "5173:5173"

  db: 
    image: postgres:17.1
    volumes: 
      - db-data:/var/lib/postgresql/data
    ports: 
    # default port for postgres
      - 5432:5432
    environment: 
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=temp
    healthcheck: 
    # checks that database is up/healthy
      test: ["CMD", "pg_isready", "-U", "user", "-d", "db", "-h", "localhost", "-p", "5432"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes: 
  db-data: 
